# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Quarkus
email:
description: >- # this means to ignore newlines until "baseurl:"
  Quarkus: Supersonic Subatomic Java
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quarkus.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: quarkusio
github_username:  quarkusio
github_fork_url: "https://github.com/quarkusio/quarkus"
# The language code for this website, used in particular for search.quarkus.io.
# See https://github.com/quarkusio/search.quarkus.io/blob/main/src/main/java/io/quarkus/search/app/entity/Language.java
language: en
search:
  # The script mode is direct or cached. Cached means the search script is copied from the remote service.
  script-mode: "cached"
  # The URL of the remote search service
  host: "https://search.quarkus.io"
  # The path to the search script (relative from the search.host)
  script-path: "/static/bundle/app.js"
  # Where to copy the search script file for cached mode
  cached-script-file: "assets/javascript/search-wc.js"
  # The amount of time before we give up on a pending remote search and fall back to Javascript search.
  # The search service itself is reasonably fast on a decent machine (with curl: ~100ms median, ~150ms 90th percentile).
  # but it's slower on prod machines (with curl: ~200ms median, ~400ms 90th percentile),
  # and prod network overhead makes it even worse (with curl from France: ~750ms median, ~1000ms 90th percentile),
  # so we need a high timeout with some margin for varying network latency depending on browser location.
  # Such a high timeout is acceptable since Javascript search is almost instantaneous,
  # so when we hit the timeout the user won't experience much more delay.
  # See also https://docs.google.com/spreadsheets/d/1w0tSfL-MKFArSrB-L8IX1pxmrhWmQyNgNwQRloG3cLk/edit#gid=456110917
  initial-timeout: 1500
  # When fetching more pages, a timeout would be very bad for UX
  # since we would reset the whole page using Javascript --
  # while the user is reading through it!
  # This we set a higher timeout value, to make timeouts less likely.
  more-timeout: 2500
  # The minimum number of characters before we run a full search.
  # Below this:
  # - if another filter is selected (e.g. categories), we run Javascript search
  # - otherwise, we don't run search and just display all guides
  min-chars: 2

# Build settings
error_mode: strict
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-auto-authors

keep_files:
  - assets/javascripts/search-wc.js

sass:
  style: compressed

collections:
  guides:
    output: true
  redirects:
    output: true
    permalink: /:path/
  versions:
    output: true
    permalink: /version/:path

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    source-highlighter: highlightjs
    sectanchors: ''
    icons: font
    outfilesuffix: ''
    add-copy-button-to-env-var: true
    add-copy-button-to-config-props: true

# Pages permalink
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "guides" # previously `post` in Jekyll 2.2.
    values:
      layout: "guides"
      permalink: /guides/:name
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "versions"
    values:
      layout: "guides"
      permalink: /version/:path
  -
    scope:
      type: "posts"
    values:
      permalink: /blog/:title/
  -
    scope:
      type: redirects
    values:
      layout: redirect

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default descending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  # extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  # indexpage: 'index'

############################################################

autopages:
  enabled: true
  categories:
    enabled: false
  tags:
    enabled: false
  collections:
    enabled: false

  # Add this block
  authors:
    enabled: true
    data: '_data/authors.yaml' # Data file with the author details
    # Uncomment the line below to force exclude certain authors from autopage generation.
    # exclude: [ "author1", "author2" ]
    layouts:
      - 'author.html' # We'll define this layout later
    title: 'Posts by :author'
    permalink: '/author/:author/'
    slugify:
      mode: 'default' # choose from [raw, default, pretty, ascii or latin]
      cased: true # if true, the uppercase letters in slug will be converted to lowercase ones.


# Scholar / Bibliography
publication:
  group_by: type
  sort_by: date
  #order: descending
  #group_order: type
  #type_order: [article, video, podcast]
  type_names:
    article: Article & Blogs
    podcast: Podcasts
    video: Videos
    training: Training
    book: Books

############################################################

# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive
  permalinks:
    tag: '/blog/tag/:name/'


############################################################
feed:
  posts_limit: 50

include:
  - ".well-known"
