name: deploy

on:
  push: 
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-publish
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - name: install-commands
        env: 
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        run: |
          sudo apt-get install -qq sshpass
          gem install bundler -v 2.0.2
          bundle config path vendor/bundle
      - uses: actions/cache@v1
        id: cache-gems
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - uses: actions/cache@v1
        id: cache-jekyll
        with:
          path: .jekyll-cache
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: install dependencies
        if: steps.cache-gems.outputs.cache-hit != 'true'
        env: 
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        run: | 
          bundle install --jobs 4 --retry 3
      - name: jekyll-build
        env: 
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        run: bundle exec jekyll build
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          keep_history: true
          build_dir: _site
          target_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}