name: Sync main documentation

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - uses: actions/checkout@v2
        with:
          repository: quarkusio/quarkus
          path: .quarkus-main-repository

      - name: Set up JDK 11
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: 11
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-pr-${{ runner.os }}-${{ steps.get-date.outputs.date }}
      - name: Build generated documentation
        working-directory: .quarkus-main-repository
        run: ./mvnw -B -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests clean install

      - name: Rebase before rsync
        run: |
          git pull origin develop --rebase
 
      - name: Sync guides
        run: |
          rsync -vr --delete \
            --exclude='**/*.html' \
            --exclude='**/index.adoc' \
            --exclude='**/attributes.adoc' \
            --exclude='**/guides.md' \
            .quarkus-main-repository/docs/src/main/asciidoc/* \
            _versions/main/guides/
      - name: Sync generated documentation
        run: |
          rsync -vr --delete \
            .quarkus-main-repository/target/asciidoc/generated/ \
            _generated-config/main

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Commit changes
        run: |
          git add .
          git commit -am "Sync documentation of main branch"
          git pull origin develop --rebase
      - name: Push changes to develop
        # Uses sha for added security since tags can be updated
        uses: ad-m/github-push-action@057a6ba835d986bfe495dd476a6c4db1d5f9503c
        with:
          github_token: ${{ secrets.SYNC_MAIN_TOKEN }}
          branch: develop

      - name: Report status
        if: "always() && github.repository == 'quarkusio/quarkusio.github.io'"
        shell: bash
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          ~/.jbang/bin/jbang .github/report-status-in-issue.java \
            issueNumber=17071 \
            runId=${{ github.run_id }} \
            status=${{ job.status }} \
            token=${{ secrets.SYNC_MAIN_TOKEN }} \
            issueRepo=quarkusio/quarkus \
            thisRepo=${{ github.repository }}
