name: Sync working groups

env:
  JVM_VERSION: '21'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  sync:
    if: github.repository == 'quarkusio/quarkusio.github.io'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - name: Install JDK ${{ env.JVM_VERSION }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JVM_VERSION }}

      - name: Set up JBang
        uses: jbangdev/setup-jbang@main

      - name: Run script
        run: |
          jbang --java ${JVM_VERSION} -Dworking-groups.output=_data/wg.yaml working-groups/main.java
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_WORKING_GROUP_TOKEN }}

      - name: Configure Git author
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"

      - name: Commit changes
        shell: bash
        run: |
            git add _data/wg.yaml
            if [ -n "$(git status --porcelain)" ]; then
              git commit -am "Sync working groups"
            fi
            git pull origin main --rebase
            git push origin main
